### ISSUE TITLE
Is Emacswiki acceptable as source of repository?

### ISSUE THREAD

**Issue by ROCKTAKEY** [conao3/celpa#4]
Many packages are buried in Emacswiki, so I think it it should be acceptable.
What do you think about this, @conao3 ?

**Comment by conao3** [comment]
I think can't.
Please create a separate repository and push your(someone) code. (I recommend GitHub)
This scheme helps us with more code collaboration.

**Comment by ROCKTAKEY** [comment]
I want add `dired+`, but this package is updated in Dec, 2019.  So This pacakge can be updated soon. Separating obsoleted package must be good, but separating active package might not be good. 
Maybe, some other packages in Emacswiki is in same state.

Pulling from ![emacsmirror](https://github.com/emacsmirror), which is github repository, can be one of choices.

**Comment by conao3** [comment]
If Emacswiki's upstream is still being updated, you might want to write a small script to have it automatically pull into your repository.
I would like to confirm that CELPA is not official (all Emacs user wide), it is a temporary and orphaned archive for hackers.

**Comment by conao3** [comment]
Is it technically possible to get it from Emacswiki in the first place? I don't want to touch the MELPA code too much (If we leave MELPA too far, we won't be able to auto-merge).

**Comment by ROCKTAKEY** [comment]
>Is it technically possible to get it from Emacswiki in the first place? 

I think I can, with github actions.
I'm going to make an organization, emacswikier, which pull repositories from registered URLs every some minutes. Do you agree with this plan?

**Comment by conao3** [comment]
Just information, this issue had solved adding emacsmirrors `dired+` GitHub repository at #5.
